import { RPCProviders, SupportedNetworks } from "./types.js";

export const RPC_ENDPOINTS = new Map<
  RPCProviders,
  Partial<Record<SupportedNetworks, string>>
>();

RPC_ENDPOINTS.set("alchemy", {
  mainnet: "https://eth-mainnet.g.alchemy.com/v2/{{apiKey}}",
  sepolia: "https://eth-sepolia.g.alchemy.com/v2/{{apiKey}}",
  arbitrum: "https://arb-mainnet.g.alchemy.com/v2/{{apiKey}}",
  arbitrumSepolia: "https://arb-sepolia.g.alchemy.com/v2/{{apiKey}}",
  avalanche: "https://avax-mainnet.g.alchemy.com/v2/{{apiKey}}",
  base: "https://base-mainnet.g.alchemy.com/v2/{{apiKey}}",
  baseSepolia: "https://base-sepolia.g.alchemy.com/v2/{{apiKey}}",
  bsc: "https://bnb-mainnet.g.alchemy.com/v2/{{apiKey}}",
  celo: "https://celo-mainnet.g.alchemy.com/v2/{{apiKey}}",
  linea: "https://linea-mainnet.g.alchemy.com/v2/{{apiKey}}",
  optimism: "https://opt-mainnet.g.alchemy.com/v2/{{apiKey}}",
  optimismSepolia: "https://opt-sepolia.g.alchemy.com/v2/{{apiKey}}",
  polygon: "https://polygon-mainnet.g.alchemy.com/v2/{{apiKey}}",
  gnosis: "https://gnosis-mainnet.g.alchemy.com/v2/{{apiKey}}",
  sonic: "https://sonic-mainnet.g.alchemy.com/v2/{{apiKey}}",
  unichain: "https://unichain-mainnet.g.alchemy.com/v2/{{apiKey}}",
  mantle: "https://mantle-mainnet.g.alchemy.com/v2/{{apiKey}}",
  zksync: "https://zksync-mainnet.g.alchemy.com/v2/{{apiKey}}",
  solana: "https://solana-mainnet.g.alchemy.com/v2/{{apiKey}}",
});

RPC_ENDPOINTS.set("infura", {
  mainnet: "https://mainnet.infura.io/v3/{{apiKey}}",
  sepolia: "https://sepolia.infura.io/v3/{{apiKey}}",
  arbitrum: "https://arbitrum-mainnet.infura.io/v3/{{apiKey}}",
  arbitrumSepolia: "https://arbitrum-sepolia.infura.io/v3/{{apiKey}}",
  avalanche: "https://avalanche-mainnet.infura.io/v3/{{apiKey}}",
  base: "https://base-mainnet.infura.io/v3/{{apiKey}}",
  baseSepolia: "https://base-sepolia.infura.io/v3/{{apiKey}}",
  bsc: "https://bsc-mainnet.infura.io/v3/{{apiKey}}",
  celo: "https://celo-mainnet.infura.io/v3/{{apiKey}}",
  linea: "https://linea-mainnet.infura.io/v3/{{apiKey}}",
  optimism: "https://optimism-mainnet.infura.io/v3/{{apiKey}}",
  optimismSepolia: "https://optimism-sepolia.infura.io/v3/{{apiKey}}",
  polygon: "https://polygon-mainnet.infura.io/v3/{{apiKey}}",
  unichain: "https://unichain-mainnet.infura.io/v3/{{apiKey}}",
  zksync: "https://zksync-mainnet.infura.io/v3/{{apiKey}}",
  mantle: "https://mantle-mainnet.infura.io/v3/{{apiKey}}",
});

RPC_ENDPOINTS.set("ankr", {
  mainnet: "https://rpc.ankr.com/eth/{{apiKey}}",
  sepolia: "https://rpc.ankr.com/eth_sepolia/{{apiKey}}",
  arbitrum: "https://rpc.ankr.com/arbitrum/{{apiKey}}",
  arbitrumSepolia: "https://rpc.ankr.com/arbitrum_sepolia/{{apiKey}}",
  avalanche: "https://rpc.ankr.com/avalanche-c/{{apiKey}}",
  base: "https://rpc.ankr.com/base/{{apiKey}}",
  baseSepolia: "https://rpc.ankr.com/base_sepolia/{{apiKey}}",
  bsc: "https://rpc.ankr.com/bsc/{{apiKey}}",
  celo: "https://rpc.ankr.com/celo/{{apiKey}}",
  linea: "https://rpc.ankr.com/linea/{{apiKey}}",
  optimism: "https://rpc.ankr.com/optimism/{{apiKey}}",
  optimismSepolia: "https://rpc.ankr.com/optimism_sepolia/{{apiKey}}",
  polygon: "https://rpc.ankr.com/polygon/{{apiKey}}",
  gnosis: "https://rpc.ankr.com/gnosis/{{apiKey}}",
  sonic: "https://rpc.ankr.com/sonic_mainnet/{{apiKey}}",
  zksync: "https://rpc.ankr.com/zksync_era/{{apiKey}}",
  mantle: "https://rpc.ankr.com/mantle_mainnet/{{apiKey}}",
  solana: "https://rpc.ankr.com/solana_mainnet/{{apiKey}}",
});

RPC_ENDPOINTS.set("chainstack", {
  mainnet: "https://ethereum-mainnet.core.chainstack.com/{{apiKey}}",
  sepolia: "https://ethereum-sepolia.core.chainstack.com/{{apiKey}}",
  arbitrum: "https://arbitrum-mainnet.core.chainstack.com/{{apiKey}}",
  arbitrumSepolia: "https://arbitrum-sepolia.core.chainstack.com/{{apiKey}}",
  avalanche:
    "https://avalanche-mainnet.core.chainstack.com/ext/bc/C/rpc/{{apiKey}}",
  base: "https://base-mainnet.core.chainstack.com/{{apiKey}}",
  baseSepolia: "https://base-sepolia.core.chainstack.com/{{apiKey}}",
  bsc: "https://bsc-mainnet.core.chainstack.com/{{apiKey}}",
  celo: "https://celo-mainnet.core.chainstack.com/{{apiKey}}",
  linea: "https://linea-mainnet.core.chainstack.com/{{apiKey}}",
  optimism: "https://optimism-mainnet.core.chainstack.com/{{apiKey}}",
  optimismSepolia: "https://optimism-sepolia.core.chainstack.com/{{apiKey}}",
  polygon: "https://polygon-mainnet.core.chainstack.com/{{apiKey}}",
  gnosis: "https://gnosis-mainnet.core.chainstack.com/{{apiKey}}",
  sonic: "https://sonic-mainnet.core.chainstack.com/{{apiKey}}",
  unichain: "https://unichain-mainnet.core.chainstack.com/{{apiKey}}",
  zksync: "https://zksync-mainnet.core.chainstack.com/{{apiKey}}",
  mantle: "https://mantle-mainnet.core.chainstack.com/{{apiKey}}",
  solana: "https://solana-mainnet.core.chainstack.com/{{apiKey}}",
});

RPC_ENDPOINTS.set("quicknode", {
  mainnet: "https://{{endpointName}}.quiknode.pro/{{apiKey}}",
  sepolia: "https://{{endpointName}}.ethereum-sepolia.quiknode.pro/{{apiKey}}",
  arbitrum: "https://{{endpointName}}.arbitrum-mainnet.quiknode.pro/{{apiKey}}",
  arbitrumSepolia:
    "https://{{endpointName}}.arbitrum-sepolia.quiknode.pro/{{apiKey}}",
  avalanche:
    "https://{{endpointName}}.avalanche-mainnet.quiknode.pro/ext/bc/C/rpc/{{apiKey}}",
  base: "https://{{endpointName}}.base-mainnet.quiknode.pro/{{apiKey}}",
  baseSepolia: "https://{{endpointName}}.base-sepolia.quiknode.pro/{{apiKey}}",
  bsc: "https://{{endpointName}}.bsc.quiknode.pro/{{apiKey}}",
  celo: "https://{{endpointName}}.celo-mainnet.quiknode.pro/{{apiKey}}",
  linea: "https://{{endpointName}}.linea-mainnet.quiknode.pro/{{apiKey}}",
  optimism: "https://{{endpointName}}.optimism.quiknode.pro/{{apiKey}}",
  optimismSepolia:
    "https://{{endpointName}}.optimism-sepolia.quiknode.pro/{{apiKey}}",
  polygon: "https://{{endpointName}}.matic.quiknode.pro/{{apiKey}}",
  gnosis: "https://{{endpointName}}.xdai.quiknode.pro/{{apiKey}}",
  unichain: "https://{{endpointName}}.unichain-mainnet.quiknode.pro/{{apiKey}}",
  zksync: "https://{{endpointName}}.zksync-mainnet.quiknode.pro/{{apiKey}}",
  mantle: "https://{{endpointName}}.mantle-mainnet.quiknode.pro/{{apiKey}}",
  solana: "https://{{endpointName}}.solana-mainnet.quiknode.pro/{{apiKey}}",
});

export const RPC_PROVIDER_URLS_BY_CHAIN_ID = {
  alchemy: {
    1: "https://eth-mainnet.g.alchemy.com/v2/{{apiKey}}",
    11155111: "https://eth-sepolia.g.alchemy.com/v2/{{apiKey}}",
    42161: "https://arb-mainnet.g.alchemy.com/v2/{{apiKey}}",
    421614: "https://arb-sepolia.g.alchemy.com/v2/{{apiKey}}",
    43114: "https://avax-mainnet.g.alchemy.com/v2/{{apiKey}}",
    8453: "https://base-mainnet.g.alchemy.com/v2/{{apiKey}}",
    84532: "https://base-sepolia.g.alchemy.com/v2/{{apiKey}}",
    56: "https://bnb-mainnet.g.alchemy.com/v2/{{apiKey}}",
    97: "https://bnb-testnet.g.alchemy.com/v2/{{apiKey}}",
    42220: "https://celo-mainnet.g.alchemy.com/v2/{{apiKey}}",
    250: "https://fantom-mainnet.g.alchemy.com/v2/{{apiKey}}",
    59144: "https://linea-mainnet.g.alchemy.com/v2/{{apiKey}}",
    10: "https://opt-mainnet.g.alchemy.com/v2/{{apiKey}}",
    11155420: "https://opt-sepolia.g.alchemy.com/v2/{{apiKey}}",
    137: "https://polygon-mainnet.g.alchemy.com/v2/{{apiKey}}",
    100: "https://gnosis-mainnet.g.alchemy.com/v2/{{apiKey}}",
    146: "https://sonic-mainnet.g.alchemy.com/v2/{{apiKey}}",
  },
  infura: {
    1: "https://mainnet.infura.io/v3/{{apiKey}}",
    11155111: "https://sepolia.infura.io/v3/{{apiKey}}",
    42161: "https://arbitrum-mainnet.infura.io/v3/{{apiKey}}",
    421614: "https://arbitrum-sepolia.infura.io/v3/{{apiKey}}",
    43114: "https://avalanche-mainnet.infura.io/v3/{{apiKey}}",
    8453: "https://base-mainnet.infura.io/v3/{{apiKey}}",
    84532: "https://base-sepolia.infura.io/v3/{{apiKey}}",
    56: "https://bsc-mainnet.infura.io/v3/{{apiKey}}",
    97: "https://bsc-testnet.infura.io/v3/{{apiKey}}",
    42220: "https://celo-mainnet.infura.io/v3/{{apiKey}}",
    59144: "https://linea-mainnet.infura.io/v3/{{apiKey}}",
    10: "https://optimism-mainnet.infura.io/v3/{{apiKey}}",
    11155420: "https://optimism-sepolia.infura.io/v3/{{apiKey}}",
    137: "https://polygon-mainnet.infura.io/v3/{{apiKey}}",
  },
  quicknode: {
    1: "https://{{endpointName}}.quiknode.pro/{{apiKey}}",
    11155111:
      "https://{{endpointName}}.ethereum-sepolia.quiknode.pro/{{apiKey}}",
    42161: "https://{{endpointName}}.arbitrum-mainnet.quiknode.pro/{{apiKey}}",
    421614: "https://{{endpointName}}.arbitrum-sepolia.quiknode.pro/{{apiKey}}",
    43114:
      "https://{{endpointName}}.avalanche-mainnet.quiknode.pro/ext/bc/C/rpc/{{apiKey}}",
    8453: "https://{{endpointName}}.base-mainnet.quiknode.pro/{{apiKey}}",
    84532: "https://{{endpointName}}.base-sepolia.quiknode.pro/{{apiKey}}",
    56: "https://{{endpointName}}.bsc.quiknode.pro/{{apiKey}}",
    97: "https://{{endpointName}}.bsc-testnet.quiknode.pro/{{apiKey}}",
    42220: "https://{{endpointName}}.celo-mainnet.quiknode.pro/{{apiKey}}",
    250: "https://{{endpointName}}.fantom.quiknode.pro/{{apiKey}}",
    59144: "https://{{endpointName}}.linea-mainnet.quiknode.pro/{{apiKey}}",
    10: "https://{{endpointName}}.optimism.quiknode.pro/{{apiKey}}",
    11155420:
      "https://{{endpointName}}.optimism-sepolia.quiknode.pro/{{apiKey}}",
    137: "https://{{endpointName}}.matic.quiknode.pro/{{apiKey}}",
    100: "https://{{endpointName}}.xdai.quiknode.pro/{{apiKey}}",
  },
  ankr: {
    1: "https://rpc.ankr.com/eth/{{apiKey}}",
    11155111: "https://rpc.ankr.com/eth_sepolia/{{apiKey}}",
    42161: "https://rpc.ankr.com/arbitrum/{{apiKey}}",
    421614: "https://rpc.ankr.com/arbitrum_sepolia/{{apiKey}}",
    43114: "https://rpc.ankr.com/avalanche-c/{{apiKey}}",
    8453: "https://rpc.ankr.com/base/{{apiKey}}",
    84532: "https://rpc.ankr.com/base_sepolia/{{apiKey}}",
    56: "https://rpc.ankr.com/bsc/{{apiKey}}",
    97: "https://rpc.ankr.com/bsc_testnet_chapel/{{apiKey}}",
    42220: "https://rpc.ankr.com/celo/{{apiKey}}",
    250: "https://rpc.ankr.com/fantom/{{apiKey}}",
    59144: "https://rpc.ankr.com/linea/{{apiKey}}",
    10: "https://rpc.ankr.com/optimism/{{apiKey}}",
    11155420: "https://rpc.ankr.com/optimism_sepolia/{{apiKey}}",
    137: "https://rpc.ankr.com/polygon/{{apiKey}}",
    100: "https://rpc.ankr.com/gnosis/{{apiKey}}",
    146: "https://rpc.ankr.com/sonic_mainnet/{{apiKey}}",
  },
  chainstack: {
    1: "https://ethereum-mainnet.core.chainstack.com/{{apiKey}}",
    11155111: "https://ethereum-sepolia.core.chainstack.com/{{apiKey}}",
    42161: "https://arbitrum-mainnet.core.chainstack.com/{{apiKey}}",
    421614: "https://arbitrum-sepolia.core.chainstack.com/{{apiKey}}",
    43114:
      "https://avalanche-mainnet.core.chainstack.com/ext/bc/C/rpc/{{apiKey}}",
    8453: "https://base-mainnet.core.chainstack.com/{{apiKey}}",
    84532: "https://base-sepolia.core.chainstack.com/{{apiKey}}",
    56: "https://bsc-mainnet.core.chainstack.com/{{apiKey}}",
    97: "https://bsc-testnet.core.chainstack.com/{{apiKey}}",
    42220: "https://celo-mainnet.core.chainstack.com/{{apiKey}}",
    250: "https://fantom-mainnet.core.chainstack.com/{{apiKey}}",
    59144: "https://linea-mainnet.core.chainstack.com/{{apiKey}}",
    10: "https://optimism-mainnet.core.chainstack.com/{{apiKey}}",
    11155420: "https://optimism-sepolia.core.chainstack.com/{{apiKey}}",
    137: "https://polygon-mainnet.core.chainstack.com/{{apiKey}}",
    100: "https://gnosis-mainnet.core.chainstack.com/{{apiKey}}",
    146: "https://sonic-mainnet.core.chainstack.com/{{apiKey}}",
  },
};
